version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./task-manager/Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./task-manager:/usr/src/app
    restart: unless-stopped
